export const CHECKOUT_REQUEST = "CHECKOUT_REQUEST";
export const CHECKOUT_SUCCESS = "CHECKOUT_SUCCESS";
export const CHECKOUT_FAIL = "CHECKOUT_FAIL";

export const SAVE_PAYMENT_METHOD_REQUEST = "SAVE_PAYMENT_METHOD_REQUEST";
export const SAVE_PAYMENT_METHOD_SUCCESS = "SAVE_PAYMENT_METHOD_SUCCESS";
export const SAVE_PAYMENT_METHOD_FAIL = "SAVE_PAYMENT_METHOD_FAIL";

export const SAVE_SHIPPING_ADDRESS_REQUEST = "SAVE_SHIPPING_ADDRESS_REQUEST";
export const SAVE_SHIPPING_ADDRESS_SUCCESS = "SAVE_SHIPPING_ADDRESS_SUCCESS";
export const SAVE_SHIPPING_ADDRESS_FAIL = "SAVE_SHIPPING_ADDRESS_FAIL";

export const CONFIRM_ORDER_REQUEST = "CONFIRM_ORDER_REQUEST";
export const CONFIRM_ORDER_SUCCESS = "CONFIRM_ORDER_SUCCESS";
export const CONFIRM_ORDER_FAIL = "CONFIRM_ORDER_FAIL";