export const INVOICE_LIST_REQUEST = 'INVOICE_LIST_REQUEST';
export const INVOICE_LIST_SUCCESS = 'INVOICE_LIST_SUCCESS';
export const INVOICE_LIST_FAIL = 'INVOICE_LIST_FAIL';

export const INVOICE_SAVE_REQUEST = 'INVOICE_SAVE_REQUEST';
export const INVOICE_SAVE_SUCCESS = 'INVOICE_SAVE_SUCCESS';
export const INVOICE_SAVE_FAIL = 'INVOICE_SAVE_FAIL';

export const INVOICE_DELETE_REQUEST = 'INVOICE_DELETE_REQUEST';
export const INVOICE_DELETE_SUCCESS = 'INVOICE_DELETE_SUCCESS';
export const INVOICE_DELETE_FAIL = 'INVOICE_DELETE_FAIL';